# True color support
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*:RGB"

# Mouse and clipboard support
set -g mouse on
set -g set-clipboard on

# Send focus events to splits
set -g focus-events on

# Vim like pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload config
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Change from 0 based to 1 based because keyboard layout
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Vim-like copy/paste
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Status bar
set -g status-interval 1
set -g status-left "#S  "
set -g status-right "%d-%m-%Y %H:%M:%S"
set -g status-left-length 30
set -g status-right-length 30

# Bind to create new session
bind-key x kill-pane

# Bind to create new session
bind-key C command-prompt -p "New Session name:" "new-session -s '%%' -c '$HOME'"

# Switch to another session when the current one is destroyed
set -g detach-on-destroy off

# New panes and windows open on current path
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Calls Tmux Sessionizer
bind-key -r f run-shell "tmux neww tmux-sessionizer"

# Move window to the left
bind-key -n S-Left swap-window -t -1\; select-window -t -1
# Move window to the right
bind-key -n S-Right swap-window -t +1\; select-window -t +1
