# ==========================================
# General Settings
# ==========================================

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set -g focus-events on
set -sg escape-time 10
set -g detach-on-destroy off

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# ==========================================
# Status Bar & Display
# ==========================================

set -g status-interval 1
set -g status-style "bg=default,fg=brightgreen"
set -g status-left "#S  "
set -g status-right "%d-%m-%Y %H:%M:%S"
set -g status-left-length 30
set -g status-right-length 30

set -g window-status-style "fg=green,dim"
set -g window-status-current-style "fg=brightgreen,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

# ==========================================
# Keybindings
# ==========================================

# Reload config
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf \; display-message "Config reloaded"

# Vim-like pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-like pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Open panes and windows in the current directory
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Vim-like copy/paste
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'sh -c "if [ -n \"$WAYLAND_DISPLAY\" ]; then wl-copy; else xclip -in -selection clipboard; fi"'
unbind -T copy-mode-vi MouseDragEnd1Pane

# Window management
bind-key -n S-Left swap-window -t -1\; select-window -t -1
bind-key -n S-Right swap-window -t +1\; select-window -t +1
bind-key x kill-pane

# Session management
bind-key C command-prompt -p "New Session:" "new-session -s '%%' -c '$HOME'"
set -s command-alias[100] 'sessionizer=display-popup -E "tmux-sessionizer"'
bind-key -r f sessionizer
