#!/usr/bin/bash

battery_level=$(cat /sys/class/power_supply/BAT*/capacity)
baterry_status=$(cat /sys/class/power_supply/BAT*/status)
format=""

if [[ $baterry_status == "Charging" ]]; then
  format="󱐋"
fi

if ((battery_level <= 5)); then
  format="$format  $battery_level%"
elif ((battery_level < 50)); then
  format="$format  $battery_level%"
elif ((battery_level < 75)); then
  format="$format  $battery_level%"
elif ((battery_level < 100)); then
  format="$format  $battery_level%"
else
  format="$format  $battery_level%"
fi

echo "$format"
