### Rosé Pine Palette
set $base           #191724
set $surface        #1f1d2e
set $overlay        #26233a
set $muted          #6e6a86
set $subtle         #908caa
set $text           #e0def4
set $love           #eb6f92
set $gold           #f6c177
set $rose           #ebbcba
set $pine           #31748f
set $foam           #9ccfd8
set $iris           #c4a7e7

### UI Settings
set $gui_font pango:JetBrainsMono Nerd Font 10

# Disable titlebars and set default border thickness
default_border pixel 1
default_floating_border normal

# Hide borders/decorations when only one window is visible
smart_borders on
hide_edge_borders smart

### Window Decorations
# target                 border    bg        text    indicator child_border
client.focused           $iris     $base     $text   $rose     $iris
client.focused_inactive  $muted    $base     $subtle $muted    $muted
client.unfocused         $base     $base     $muted  $base     $base

### Status Bar
bar {
    position top
    font $gui_font
    status_command ~/.config/sway/scripts/status.sh
    pango_markup enabled

    colors {
        background         $base
        statusline         $text
        separator          $muted

        focused_workspace  $overlay  $overlay  $iris
        active_workspace   $surface  $surface  $subtle
        inactive_workspace $base     $base     $muted
    }
}
